blank_issues_enabled: true
contact_links:
  - name: Quer saber mais sobre o EKS?
    url: https://example.com/documentacao-eks
    about: Acesse nossa documentação
  - name: Dúvidas sobre EKS?
    url: https://example.com/comunidade-eks
    about: Verifique os tópicos da comunidade ou crie um novo tópico
  - name: Precisa de suporte sobre EKS?
    url: https://example.com/suporte-eks
    about: Acesse a página de suporte para receber auxílio
