name: Diagnostic Test
on:
  workflow_dispatch:
    inputs:
      frameworks:
        type: string
        default: '["go1-26"]'

jobs:
  call-real:
    uses: ./.github/workflows/build-base-images.yml
    with:
      aws-region: ${{ vars.AWS_REGION }}
      aws-role-arn: ${{ vars.AWS_ROLE_ARN }}
      frameworks: ${{ inputs.frameworks }}
